CONFIG_PRINTK=y
CONFIG_INIT_STACKS=y
CONFIG_TRACING=y

# This only works for 32 bit, 64 bit overloads logging
# Make sure console is available and immediate
#CONFIG_LOG=y
#CONFIG_LOG_MODE_IMMEDIATE=y
