CONFIG_APP_MOTORS=n
CONFIG_APP_INPUT=n
CONFIG_APP_IMU=n
CONFIG_NEWLIB_LIBC=n
CONFIG_CMSIS_DSP=n
CONFIG_FLASH=n
CONFIG_FLASH_MAP=n
CONFIG_NVS=n
CONFIG_SETTINGS_NVS=n
CONFIG_PWM_CAPTURE=n
CONFIG_REBOOT=n