name: Twister (riscv on capable-hub)

on:
  push:
    branches:
      - v*-cheri-branch
      - collab-cheri**
  pull_request:
    branches:
      - v*-cheri-branch
      - collab-cheri**
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Twister (${{ matrix.platform }})
    runs-on: the-capable-hub-aws-ci
    container:
      image: ghcr.io/zephyrproject-rtos/ci-repo-cache:v0.27.4.20241026 # (based on zephyr 4.1.0 )

    strategy:
      fail-fast: false
      matrix:
        platform: [qemu_riscv32, qemu_riscv64]

    steps:

      - name: Install system prerequisites
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y
          apt-get install -y \
            python3 \
            python3-venv \
            python3-dev \
            python3-pip

      - name: Inspect Python
        run: |
          python3 --version || true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: zephyr
          fetch-depth: 0

      - name: Rebase
        if: github.event_name == 'pull_request'
        env:
          BASE_REF: ${{ github.base_ref }}
          PR_HEAD: ${{ github.event.pull_request.head.sha }}
        working-directory: zephyr
        shell: bash
        run: |
          git config --global user.email "actions@zephyrproject.org"
          git config --global user.name "Github Actions"
          rm -fr ".git/rebase-apply"
          rm -fr ".git/rebase-merge"
          git rebase origin/${BASE_REF}
          git clean -f -d
          git log --graph --oneline HEAD...${PR_HEAD}

      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@f7b70269a8eb01f70c8e710891e4c94972a2f6b4 # v1.0.6
        with:
          app-path: zephyr
          toolchains: all

      - name: Build firmware
        working-directory: zephyr
        shell: bash
        run: |
          ./scripts/twister --runtime-artifact-cleanup --force-color --inline-logs \
          --retry-failed 1 --exclude-tag spdx --exclude-tag shell \
          -p ${{ matrix.platform }} \
          -T samples -T tests -v

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          if-no-files-found: ignore
          name: twister-logs-${{ matrix.platform }}
          path:
            zephyr/twister-out/**/build.log
